### ISSUE TITLE
When I run the preprocess/PA.py,I encounter the ValueError: NULL pointer access error

### ISSUE THREAD

**Issue by lh123cha** [initzhang/DUCATI_SIGMOD#6] opened 2023-12-11 05:58 UTC
I have already install the dc_dgl successfully.But I encounter this error:

![nullptraccess](https://github.com/initzhang/DUCATI_SIGMOD/assets/48644550/9d14caac-6097-4aeb-a89a-fd9da48d6e72)

**Comment by lh123cha** [comment] 2023-12-11 06:03
I have already install the dc_dgl successfully. 
![Uploading 屏幕截图 2023-12-11 140110.png…]()

**Comment by lh123cha** [comment] 2023-12-11 12:50
And I how can I get the coo.txt file like uk_coo.txt from gnnlab. I can only get samgraph/uk-2006-05/coo.bin and samgraph/twitter/coo.bin from gnnlab.

![屏幕截图 2023-12-11 204532](https://github.com/initzhang/DUCATI_SIGMOD/assets/48644550/0cdcd757-f413-43a4-a25c-9990a1cf01c8)
How can I get the coo.txt file used in preprocess/UU_UK_TW.py

**Comment by initzhang** [comment] 2023-12-12 05:39
Hi @lh123cha , thanks for your interest in our work!

> I have already install the dc_dgl successfully.But I encounter this error:

It seems that the problem is in OGB loading, could you try the following code and check the results?

```python
from ogb.nodeproppred import DglNodePropPredDataset
dataset = DglNodePropPredDataset(name='ogbn-papers100M')
```

> And I how can I get the coo.txt file like uk_coo.txt from gnnlab. I can only get samgraph/uk-2006-05/coo.bin and samgraph/twitter/coo.bin from gnnlab.

You can modify the [webgraph utility in gnnlab](https://github.com/SJTU-IPADS/fgnn-artifacts/tree/main/utility/webgraph) to (de)serialise the bin file to coo file. Specifically, you can change the [line of code](https://github.com/SJTU-IPADS/fgnn-artifacts/blob/c96e7ec8204d767152958dc63a764466e90424fd/utility/webgraph/src/main/java/ipads/samgraph/webgraph/WebgraphDecoder.java#L53) and print/save to stdout/file instead.

**Comment by lh123cha** [comment] 2023-12-13 04:16
Thank you for the answer!But when I run `run_allocate.py` on uk dataset
`CUDA_VISIBLE_DEVICES=0 python run_allocate.py --dataset uk --fanouts 15,15,15 --fake-dim 100 --total-budget 1`
The error occurs

![屏幕截图 2023-12-13 121318](https://github.com/initzhang/DUCATI_SIGMOD/assets/48644550/faf3f023-116b-46e1-8af9-07e72ccc023a)

It seems like the np.polyfit() package failed on uk dataset.But I can run successfully on twitter dataset.Is there something wrong in uk dataset?

**Comment by initzhang** [comment] 2023-12-13 05:32
I haven't encountered such problem before, but according to the error message, it seems that the program fails to fitting the curve due to large variance in the system running time? Maybe you can try the following:

(1) avoid sharing the GPU/Machine with other users, because the contention on GPU/PCIe leads to unstable system running time, which could cause the failure for np.polyfit().
(2) set `pre_batches` and `pre_epochs` to larger values (such as 1000 & 10), this can mitigate the instability of system running time.

**Comment by lh123cha** [comment] 2023-12-13 07:41
Thank for the answer!I have sloved the problem.The problem is the [total_buget is smaller than nfeat_buget](https://github.com/initzhang/DUCATI_SIGMOD/blob/376f79da2f291ceffcc6311b34c247cd09fb2bb3/DualCacheAllocator.py#L146) that cause the nfeat_stats's length is one.And it is wrong to fitting the curve with only one point.So I set --total-buget to a larger number like 10.

**Comment by initzhang** [comment] 2023-12-13 09:37
Indeed this is a corner case not covered by the current Allocator lol, I will consider add sanity check for this part maybe later. Thank you for reporting the case!

**Comment by initzhang** [comment] 2023-12-15 03:01
Hi, I have updated the script to fix the problem and I will close this issue. Please feel free to reopen it or open a new issue If you have any further problems, thanks.

**Closed as completed by initzhang** 2023-12-15 03:01 UTC
